"""The migration chain and the models must describe the same schema.

The suite builds its schema with `Base.metadata.create_all` (see conftest),
which is fast and always matches the models the queries are written against —
but it means a wrong migration cannot fail a test. Deployments run the
migrations instead, so the two are only equivalent if something checks.

Nothing did, and they had already diverged: `ck_memory_versions_status_valid`
was declared on the model and enforced in tests, while every migrated database
lacked it, because a420524ae0f1 added the column with an autogenerated
`op.add_column` and Alembic's autogenerate does not emit CHECK constraints.
`alembic check` reports "No new upgrade operations detected" for exactly that
reason, so it cannot stand in for this test.
"""

import os
import subprocess
import sys
from pathlib import Path

import asyncpg
from sqlalchemy.ext.asyncio import create_async_engine

from sleeper_service.db import models  # noqa: F401  — register all tables
from sleeper_service.db.base import Base
from tests.conftest import _PG

REPO_ROOT = Path(__file__).resolve().parent.parent

_ALEMBIC_DB = "sleeper_schema_alembic"
_MODELS_DB = "sleeper_schema_models"

# Ordering is deliberately not compared: `op.add_column` appends while
# `create_all` uses model order, so the two disagree on `ordinal_position` for
# every column ever added by a migration. That difference is invisible to the
# ORM and to every query in the codebase.
_COLUMNS = """
select table_name || '.' || column_name || ' :: ' || data_type
       || ' null=' || is_nullable
       || ' default=' || coalesce(column_default, '-')
from information_schema.columns
where table_schema = 'public' and table_name <> 'alembic_version'
order by 1
"""

_CONSTRAINTS = """
select conrelid::regclass::text || ' :: ' || contype::text || ' :: ' || conname
       || ' :: ' || pg_get_constraintdef(oid)
from pg_constraint
where connamespace = 'public'::regnamespace
  and conrelid::regclass::text <> 'alembic_version'
order by 1
"""

_INDEXES = """
select tablename || ' :: ' || indexdef
from pg_indexes
where schemaname = 'public' and tablename <> 'alembic_version'
order by 1
"""


async def _recreate(admin: asyncpg.Connection, name: str) -> None:
    await admin.execute(f'drop database if exists "{name}"')
    await admin.execute(f'create database "{name}"')


def _url(name: str) -> str:
    return f"postgresql+asyncpg://sleeper:sleeper@localhost:{_PG}/{name}"


async def _catalog(name: str) -> dict[str, list[str]]:
    conn = await asyncpg.connect(f"postgresql://sleeper:sleeper@localhost:{_PG}/{name}")
    try:
        return {
            label: [r[0] for r in await conn.fetch(q)]
            for label, q in (
                ("columns", _COLUMNS),
                ("constraints", _CONSTRAINTS),
                ("indexes", _INDEXES),
            )
        }
    finally:
        await conn.close()


async def test_migrations_and_models_agree() -> None:
    admin = await asyncpg.connect(f"postgresql://sleeper:sleeper@localhost:{_PG}/sleeper")
    try:
        await _recreate(admin, _ALEMBIC_DB)
        await _recreate(admin, _MODELS_DB)

        # Alembic runs in a subprocess because env.py drives the async engine
        # with asyncio.run(), which cannot be called from inside the running
        # test loop. It is also how migrations are actually invoked.
        result = subprocess.run(
            [sys.executable, "-m", "alembic", "upgrade", "head"],
            cwd=REPO_ROOT,
            env={**os.environ, "DATABASE_URL": _url(_ALEMBIC_DB)},
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, f"alembic upgrade head failed:\n{result.stderr}"

        engine = create_async_engine(_url(_MODELS_DB))
        try:
            async with engine.begin() as conn:
                await conn.run_sync(Base.metadata.create_all)
        finally:
            await engine.dispose()

        migrated = await _catalog(_ALEMBIC_DB)
        declared = await _catalog(_MODELS_DB)

        for label in ("columns", "constraints", "indexes"):
            only_migrated = sorted(set(migrated[label]) - set(declared[label]))
            only_declared = sorted(set(declared[label]) - set(migrated[label]))
            assert not (only_migrated or only_declared), (
                f"{label} differ between the migration chain and the models.\n"
                f"A migration is missing or wrong — fix the migration, not this test.\n"
                f"  only in migrated schema: {only_migrated}\n"
                f"  only in models:          {only_declared}"
            )
    finally:
        for name in (_ALEMBIC_DB, _MODELS_DB):
            await admin.execute(f'drop database if exists "{name}"')
        await admin.close()


async def test_migration_chain_downgrades_cleanly() -> None:
    """Every downgrade actually reverses its upgrade, all the way to base.

    A downgrade that raises is easy to miss: it rolls back, so the database is
    left consistent and `alembic current` still reports a sane revision — the
    failure only shows in stderr. This branch shipped one such bug (a
    `drop_constraint` passed the fully-qualified constraint name, which the
    metadata naming convention then expanded a second time), and it survived a
    hand-check that grepped for the "Running downgrade" line.

    Reaching base with nothing but `alembic_version` left is the assertion that
    catches it: if any downgrade raises, the walk stops early and tables remain.
    """
    admin = await asyncpg.connect(f"postgresql://sleeper:sleeper@localhost:{_PG}/sleeper")
    try:
        await _recreate(admin, _ALEMBIC_DB)
        env = {**os.environ, "DATABASE_URL": _url(_ALEMBIC_DB)}
        for direction, target in (("upgrade", "head"), ("downgrade", "base")):
            result = subprocess.run(
                [sys.executable, "-m", "alembic", direction, target],
                cwd=REPO_ROOT,
                env=env,
                capture_output=True,
                text=True,
            )
            assert result.returncode == 0, f"alembic {direction} {target} failed:\n{result.stderr}"

        conn = await asyncpg.connect(f"postgresql://sleeper:sleeper@localhost:{_PG}/{_ALEMBIC_DB}")
        try:
            left = [
                r[0]
                for r in await conn.fetch(
                    "select tablename from pg_tables "
                    "where schemaname = 'public' and tablename <> 'alembic_version' "
                    "order by 1"
                )
            ]
        finally:
            await conn.close()
        assert not left, f"downgrade to base left tables behind: {left}"
    finally:
        await admin.execute(f'drop database if exists "{_ALEMBIC_DB}"')
        await admin.close()
