"""oidc configs

Revision ID: 2adce1965843
Revises: 8c9d4c07f9bb
Create Date: 2026-08-02 20:29:13.295644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2adce1965843'
down_revision: Union[str, Sequence[str], None] = '8c9d4c07f9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oidc_configs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_secret_enc', sa.LargeBinary(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_oidc_configs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oidc_configs')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_oidc_configs_tenant_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oidc_configs')
    # ### end Alembic commands ###
