"""agent archive

Revision ID: 560d0a73c748
Revises: 91b8df4e2c1a
Create Date: 2026-08-23 09:23:42.548886

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "560d0a73c748"
down_revision: Union[str, Sequence[str], None] = "91b8df4e2c1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_agents_archived_at"), "agents", ["archived_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agents_archived_at"), table_name="agents")
    op.drop_column("agents", "archived_at")
    # ### end Alembic commands ###
