"""version aliases

Revision ID: 8c9d4c07f9bb
Revises: a420524ae0f1
Create Date: 2026-08-02 18:46:10.831510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c9d4c07f9bb"
down_revision: Union[str, Sequence[str], None] = "a420524ae0f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "version_aliases",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("agent_version_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_version_aliases_agent_id_agents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_version_aliases_agent_version_id_agent_versions"),
        ),
        sa.PrimaryKeyConstraint("agent_id", "alias", name=op.f("pk_version_aliases")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("version_aliases")
    # ### end Alembic commands ###
