"""add the missing ck_memory_versions_status_valid constraint

The constraint is declared on the model (`MemoryVersion.__table_args__`) and so
has always existed in databases built by `Base.metadata.create_all` — which is
how the test suite builds its schema. It never existed in a database built by
migrations, because a420524ae0f1 added `memory_versions.status` with an
autogenerated `op.add_column` and Alembic's autogenerate does not emit CHECK
constraints. The two schemas therefore disagreed on exactly one thing: tests
rejected an out-of-range status, deployments accepted it.

tests/test_migrations.py now compares the two schemas so the next omission of
this kind fails CI instead of waiting to be noticed.

Revision ID: b4a1f2e83c67
Revises: d3f5a91c07be
Create Date: 2026-08-25 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4a1f2e83c67"
down_revision: Union[str, Sequence[str], None] = "d3f5a91c07be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Named to match what the metadata's naming convention produces for
    # CheckConstraint(name="status_valid") on this table, since the whole point
    # is for the two schemas to agree.
    op.create_check_constraint(
        "status_valid",
        "memory_versions",
        "status IN ('active', 'pending', 'rejected')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Short name, not the full one: the metadata naming convention is applied
    # here too, so passing "ck_memory_versions_status_valid" would try to drop
    # "ck_memory_versions_ck_memory_versions_status_valid".
    op.drop_constraint("status_valid", "memory_versions", type_="check")
